type User {
  "From schema string: id of the user"
  id: ID
  "From schema string: name of the user."
  name: String
}

type Query {
  getUsers: [User]
  getUser(id: ID): User
}

type Mutation {
  createUser(name: String): User
}