type User {
  "From schema string: id of the user"
  id: Int
  "From schema string: name of the user."
  name: String
  "city information of the user"
  city: City
}

type Query {
  "Query to get all the users"
  getUsers: [User]
  "Query to get user by id"
  getUser(id: Int): User
}

type Mutation {
  "Mutation to create a new user"
  createUser(name: String): User
}

type Query {
    getUser(id: Int): User
  }
  type Mutation {
    createUser(name: String): User
  }